bind C-Space send-prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key s choose-tree -NsZ
bind-key w choose-tree -NwZ
set -g base-index 1
set -g mouse on
set -g prefix C-Space
setw -g mode-keys vi
unbind -T copy-mode-vi MouseDragEnd1Pane
unbind C-b
